server {
    server_name smkn1pld.absenta.id;
    root /var/www/absenta.id; # Points to the central catch-all web client
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Prevent HTML caching so updates are live instantly
    location ~* \.(html)$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        expires -1;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/smkn1pld.absenta.id/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/smkn1pld.absenta.id/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = smkn1pld.absenta.id) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name smkn1pld.absenta.id;
    listen 80;
    return 404; # managed by Certbot
}
