[Interface]
PrivateKey = cHEzi9eLQgLXCE8lgebX8EZ9bjiQxIU9VlZiJMO5gWo=
Address = 10.0.0.2/24

[Peer]
PublicKey = SP47bTGqXxN4Qqe2DewpONtYEOh2qcXPTj7dt1g1x2o=
Endpoint = 103.103.22.144:51820
AllowedIPs = 10.0.0.1/32
PersistentKeepalive = 25
