[Interface]
PrivateKey = cA55EpJtVAQEoZdnpaqFGLdHpnZgR2COK9oveE/yAGY=
Address = 10.0.0.1/24
ListenPort = 51820

[Peer]
PublicKey = aNXX26oxSYevAh1hdhJPoc6PXmOFvTyLchUVzIC8bX8=
AllowedIPs = 10.0.0.2/32
